# Generated by Django 5.1.4 on 2024-12-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_admin_empleado_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
